<?php

declare(strict_types=1);

use PhpCsFixer\Config;

if (!file_exists(__DIR__.'/src')) {
    exit(0);
}

return (new Config())
    ->setRules([
        /* Rule sets */
        '@PHPUnit84Migration:risky' => true,
        '@PSR2' => true,
        '@PSR12' => true,
        '@Symfony' => true,
        '@Symfony:risky' => true,

        /* Rules */
        'declare_strict_types' => true,
        'no_extra_blank_lines' => [
            'tokens' => [
                'case',
                'continue',
                'curly_brace_block',
                'default',
                'extra',
                'parenthesis_brace_block',
                'square_brace_block',
                'switch',
                'throw',
                // 'use',
            ],
        ],
        'ordered_imports' => [
            'sort_algorithm' => 'alpha',
            'imports_order' => ['class', 'function', 'const'],
        ],
        'phpdoc_align' => false,
        'phpdoc_separation' => false,
        'single_line_throw' => false,
    ])
    ->setRiskyAllowed(true)
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->in(__DIR__.'/tests')
            ->in(__DIR__.'/src')
            ->append([__FILE__])
            ->exclude([
                // directories containing files with content that is autogenerated by `var_export`, which breaks CS in output code
                'Symfony/Component/DependencyInjection/Tests/Fixtures',
                'Symfony/Component/Routing/Tests/Fixtures/dumper',
                // fixture templates
                'Symfony/Component/Templating/Tests/Fixtures/templates',
                'Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom',
                // generated fixtures
                'Symfony/Component/VarDumper/Tests/Fixtures',
                // resource templates
                'Symfony/Bundle/FrameworkBundle/Resources/views/Form',
            ])
            ->notPath('vendor')
            // file content autogenerated by `var_export`
            ->notPath('Symfony/Component/Translation/Tests/fixtures/resources.php')
            // test template
            ->notPath('Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom/_name_entry_label.html.php')
            // explicit heredoc test
            ->notPath('Symfony/Bundle/FrameworkBundle/Tests/Fixtures/Resources/views/translation.html.php')
            // explicit trigger_error tests
            ->notPath('Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/default.phpt')
            ->notPath('Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/weak.phpt')
            ->notPath('Symfony/Component/Debug/Tests/DebugClassLoaderTest.php')
            // invalid annotations on purpose
            ->notPath('Symfony/Component/DependencyInjection/Tests/Fixtures/includes/autowiring_classes.php')
    );
