version: "3.5"
services:

    redis:
      image: redis:alpine
      container_name: php-redis

    mysql:
      image: mysql:5.7
      container_name: php-mysql
      volumes:
        - "./database:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: php-webserver
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./application:/application
      ports:
       - "8080:80"
      depends_on:
       - php-fpm

    php-fpm:
      image: php-fpm
      build:
        context: .
        dockerfile: php-fpm/Dockerfile
        args:
          - LOCAL_UID=${LOCAL_UID}
          - LOCAL_GID=${LOCAL_GID}
      container_name: php-fpm
      volumes:
        - ./application:/application
        - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
      links:
        - mysql:php-mysql
      environment:
        XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_enable=${XDEBUG_REMOTE_ENABLE}
        PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
        BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
        BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
        BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
            - PMA_HOST=php-mysql
        links:
            - mysql:php-mysql

